In [24]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

# from feature-engine
from feature_engine.imputation import (
    AddMissingIndicator,
    MeanMedianImputer,
    CategoricalImputer,
)

In [15]:
## load the data and get work to hande the massing value

train = pd.read_csv('../Data/CarV3.csv')

In [16]:
train.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [4]:
## get the number of the massing value form the dataset

massing = [feat for feat in list(train) if train[feat].isnull().sum() > 0]
## get the persting fo massing value from the totole number of the value

In [17]:
def split_clean(data_frame, feat, split_in):
    ## this function will get number from the string featuer
    _split_value = data_frame[feat].str.split(split_in)
    data_frame[feat] = np.float16( _split_value.str.get(0))

    return data_frame

In [12]:
massing

['mileage', 'engine', 'max_power', 'torque', 'seats']

In [18]:
train = split_clean(train, 'mileage', ' ')

In [7]:
train['mileage'].isnull().sum() / len(train) * 100 ## 2.7 is the null value of the all featuer

2.718996062992126

In [8]:
train = split_clean(train, 'mileage', ' ')

In [19]:
train = split_clean(train, 'engine', ' ')

In [22]:
totle_null = train.isnull().sum().sort_values(ascending=False) / len(train) * 100
massing = pd.DataFrame(totle_null)
massing

                      0
torque         2.731299
mileage        2.718996
engine         2.718996
seats          2.718996
max_power      2.645177
name           0.000000
year           0.000000
selling_price  0.000000
km_driven      0.000000
fuel           0.000000
seller_type    0.000000
transmission   0.000000
owner          0.000000

In [25]:
train

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.406250,1248.0,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.140625,1498.0,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.703125,1497.0,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.000000,1396.0,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.093750,1298.0,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.500000,1197.0,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.796875,1493.0,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.296875,1248.0,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.562500,1396.0,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.562500,1396.0,70 bhp,140Nm@ 1800-3000rpm,5.0

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    train.drop("selling_price", axis=1),  # just the features
    train["selling_price"],  # the target
    test_size=0.3,  # the percentage of obs in the test set
    random_state=0,  # for reproducibility
)

In [27]:
X_train#

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
5224,Tata Tiago 1.2 Revotron XT,2017,20000,Petrol,Individual,Manual,First Owner,23.843750,1199.0,84 bhp,114Nm@ 3500rpm,5.0
520,Maruti Swift Dzire 1.2 Vxi BSIV,2012,30000,Petrol,Individual,Manual,First Owner,17.500000,1197.0,85.8 bhp,114Nm@ 4000rpm,5.0
36,Maruti Alto K10 VXI Airbag,2019,15000,Petrol,Individual,Manual,First Owner,23.953125,998.0,67.1 bhp,90Nm@ 3500rpm,5.0
5782,Ford EcoSport 1.5 Diesel Trend Plus BSIV,2018,53000,Diesel,Individual,Manual,First Owner,23.000000,1498.0,98.96 bhp,205Nm@ 1750-3250rpm,5.0
6522,Chevrolet Enjoy TCDi LS 8 Seater,2015,120000,Diesel,Individual,Manual,First Owner,18.203125,1248.0,73.8 bhp,172.5Nm@ 1750rpm,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4931,Tata Manza Aura (ABS) Quadrajet BS IV,2012,70000,Diesel,Individual,Manual,Third Owner,21.125000,1248.0,88.8 bhp,200Nm@ 1750-3000rpm,5.0
3264,Ford Figo Diesel EXI,2012,100000,Diesel,Individual,Manual,Second Owner,20.000000,1399.0,68 bhp,160Nm@ 2000rpm,5.0
1653,Hyundai i10 Sportz Option,2009,90000,Petrol,Individual,Manual,Second Owner,20.359375,1197.0,78.9 bhp,111.8Nm@ 4000rpm,5.0
2607,Volkswagen Vento Diesel Highline,2012,90000,Diesel,Individual,Manual,First Owner,20.546875,1598.0,103.6 bhp,250Nm@ 1500-2500rpm,5.0
2732,Hyundai i10 Magna 1.1L,2012,110000,Petrol,Individual,Manual,First Owner,19.812500,1086.0,68.05 bhp,99.04Nm@ 4500rpm,5.0